import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of DepositTrack.",
};

const UPDATED = "June 7, 2026";
const CONTACT = "support@deposittrack.com";

export default function TermsPage() {
  return (
    <article>
      <h1>Terms of Service</h1>
      <p className="updated">Last updated: {UPDATED}</p>

      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use
        of DepositTrack&rsquo;s mobile apps, website, and related services (the
        &ldquo;Service&rdquo;). By creating an account or using the Service, you
        agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        DepositTrack helps you document property conditions with photos,
        signatures, and reports to support security-deposit protection. The Service
        is a documentation tool. It is not a substitute for professional advice and
        does not provide appraisals, code inspections, warranties, or legal
        determinations.
      </p>

      <h2>2. Eligibility and accounts</h2>
      <p>
        You must be at least 18 years old and able to form a binding contract. You
        are responsible for the activity under your account and for keeping your
        login credentials secure. You agree to provide accurate information and to
        keep it up to date.
      </p>

      <h2>3. Acceptable use</h2>
      <ul>
        <li>Do not use the Service for any unlawful or fraudulent purpose.</li>
        <li>Do not upload content you do not have the right to capture or share.</li>
        <li>Do not attempt to disrupt, reverse engineer, or gain unauthorized access to the Service.</li>
        <li>Do not misrepresent property conditions or falsify inspection records.</li>
      </ul>

      <h2>4. Your content</h2>
      <p>
        You retain ownership of the inspections, photos, notes, and other content
        you create (&ldquo;Your Content&rdquo;). You grant DepositTrack a limited
        license to host, store, process, and display Your Content solely to operate
        and provide the Service to you and the collaborators you authorize. You are
        responsible for the accuracy and lawfulness of Your Content.
      </p>

      <h2>5. Electronic signatures</h2>
      <p>
        The Service supports electronic signatures intended to comply with the U.S.
        ESIGN Act and UETA. By signing electronically, you consent to use
        electronic records and signatures and agree they have the same legal effect
        as handwritten signatures. Each signature is recorded with audit data
        (name, role, date, time, IP address, and device information).
      </p>

      <h2>6. Subscriptions and payments</h2>
      <p>
        Some features require a paid plan or a one-time purchase (for example,
        single-report or subscription tiers). Prices and plan details are presented
        in the app or on our website and may change. Purchases made through the
        Apple App Store or Google Play are also subject to those stores&rsquo;
        terms. Except where required by law, payments are non-refundable.
      </p>

      <h2>7. Disclaimers</h2>
      <p>
        Reports generated by the Service are intended to document observable
        property conditions at the time of inspection. They are not professional
        appraisals, warranties, code inspections, or legal determinations. The
        Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;
        without warranties of any kind, whether express or implied, to the fullest
        extent permitted by law.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, DepositTrack and its suppliers will
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages, or for any loss of data, profits, or goodwill arising from
        your use of the Service. Our total liability for any claim relating to the
        Service will not exceed the amount you paid us in the twelve months before
        the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time. We may
        suspend or terminate access if you violate these Terms or use the Service in
        a way that could cause harm or legal exposure.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be posted
        on this page with an updated &ldquo;Last updated&rdquo; date. Your continued
        use of the Service after changes take effect constitutes acceptance.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These Terms are governed by the laws of the United States and the state in
        which DepositTrack is established, without regard to conflict-of-law
        principles.
      </p>

      <h2>12. Contact us</h2>
      <p>
        Questions about these Terms? Email us at{" "}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
    </article>
  );
}
